### PR TITLE
update icon mui for package

### PR DESCRIPTION
**Pull request by jeffvg**
#### Changes proposed in this Pull Request:
- clean up script error for icons-mui
- 
-

### CODE REVIEW

**Comment by huayunh** [comment]
why would a package use itself as the dependency?

**Comment by jeffvg** [comment]
> why would a package use itself as the dependency?

https://github.com/pxblue/icons-mui/pull/21#issuecomment-702148742

**Comment by joebochill** [comment]
Agreed with Huayun...you shouldn't need to have the package as a dependency of itself. Are you seeing those errors on a fresh clone? The install command runs before everything else so there shouldn't be a possibility of it not being there by the time the build happens.

**Comment by jeffvg** [comment]
yes got this error on a fresh clone...

**Comment by huayunh** [comment]
lemme do it locally

**Comment by huayunh** [comment]
Cannot reproduce. Might be a PC issue?

**Pull request closed without merging**
